# Generated by Django 3.0.3 on 2020-02-25 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Listing Title', max_length=32, unique=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this listing.', max_length=32)),
                ('desc', models.TextField(help_text='Describe your critter')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date & time this listing was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date & time this listing was updated.')),
                ('type', models.CharField(choices=[('???', '???'), ('reptile', 'Reptile'), ('amphibian', 'Amphibian'), ('insect', 'Insect'), ('spider', 'Spider')], default='???', help_text='Critter Type', max_length=12)),
                ('species', models.CharField(help_text='Critter Species', max_length=24)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
