# Generated by Django 3.0.3 on 2020-03-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200303_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='age_format',
            field=models.CharField(blank=True, choices=[('YR', 'Year(s) old'), ('MO', 'Months old')], default='YR', help_text='Year/Month', max_length=2, null=True),
        ),
    ]
