# Generated by Django 3.0.3 on 2020-03-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200303_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='age_format',
        ),
        migrations.AddField(
            model_name='listing',
            name='ageFormat',
            field=models.CharField(blank=True, choices=[('YR', 'Year'), ('YRs', 'Years'), ('MO', 'Months')], help_text='Year/Month', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price (USD)', max_digits=8, null=True),
        ),
    ]
