# Generated by Django 3.0.3 on 2020-03-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200303_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='age_num',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ageFormat',
            new_name='age_Format',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('?', 'Unknown')], help_text='Critter Gender', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', help_text='Listing Title', max_length=54),
        ),
    ]
