# Generated by Django 3.0.3 on 2020-03-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200304_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='age_Format',
            field=models.CharField(blank=True, choices=[('Year', 'Year'), ('Years', 'Years'), ('Months', 'Months')], help_text='Year/Month', max_length=6, null=True),
        ),
    ]
