# Generated by Django 3.0.4 on 2020-03-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20200304_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this listing.', max_length=21),
        ),
    ]
