# Generated by Django 3.0.3 on 2020-03-04 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, editable=False, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date & time this item was posted.')),
                ('title', models.CharField(default='', help_text='Item Title', max_length=32)),
                ('info', models.TextField(help_text='Extra information about this item.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price (USD)', max_digits=8)),
                ('item_img', models.ImageField(upload_to='')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
